### ISSUE TITLE
自己编辑的角色   角色/形象ID 怎么查看

### ISSUE THREAD

**Issue by heisen16129** [WeHome007/NextCAS#1]

**Comment by WeHome007** [comment]
我想你可能是需要知道如何生成一个新的形象/角色并如何绑定道具的功能，具体的操作方法是需要调用NextHuman的服务端API进行生成，同时由“WebGL/UE”对应的SDK来提供一个saveAvatar的方法来进行保存(既然有这个需求，那我们将会近期为你提供该方法实现);
