### ISSUE TITLE
官网上的企业微信二维码无法添加

### ISSUE THREAD

**Issue by WangShaoyu1** [WeHome007/NextCAS#3]
<img width="193" alt="aee0a50dc1e988242f6f7b6e0a6d0b0" src="https://github.com/WeHome007/NextCAS/assets/16829507/28dc4e37-3dbf-45fd-92bd-d56d3378d80b">

这样的话，无法注册新账号，因为只有添加企业微信号，才能够获取邀请码；注册时邀请码是必填项。

**Comment by WeHome007** [comment]
收到，明天你试一下

**Comment by WangShaoyu1** [comment]
上午十点钟10：15，刚试了下，不行


| |
王宇
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年1月12日 23:47 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [WeHome007/NextCAS] 官网上的企业微信二维码无法添加 (Issue #3) |

收到，明天你试一下
